name: bivac
home: https://github.com/camptocamp/bivac
icon: https://raw.githubusercontent.com/camptocamp/bivac/master/img/bivac_small.png
version: 1.0.0
appVersion: latest
description: 'Backup Interface for Volumes Attached to Containers'
keywords:
  - backup
  - bivac
  - restic
  - volume
  - kubernetes
  - openshift
sources:
  - https://github.com/camptocamp/bivac
maintainers:
  - name: Camptocamp
    email: info@camptocamp.com
