apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "bivac.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "bivac.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bivac.name" . }}
        release: {{ .Release.Name }}
        {{- with .Values.labels }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: manager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bivac
            - manager
          ports:
            - name: api
              containerPort: 8182
          env:
            - name: BIVAC_ORCHESTRATOR
              value: {{ .Values.orchestrator }}
            - name: KUBERNETES_ALL_NAMESPACES
              value: "{{ .Values.watchAllNamespaces }}"
            - name: BIVAC_TARGET_URL
              value: {{ required "A target URL must be specified" .Values.targetURL }}
            - name: RESTIC_PASSWORD
              {{- if .Values.resticPassword }}
              value: {{ .Values.resticPassword }}
              {{- else }}
              value: {{ randAlphaNum 15 }}
              {{- end }}
            - name: BIVAC_SERVER_PSK
              {{- if .Values.serverPSK }}
              value: {{ .Values.serverPSK }}
              {{- else }}
              value: {{ randAlphaNum 15 }}
              {{- end }}
            - name: BIVAC_LOG_SERVER
              value: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}"
            {{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
            {{- end }}
{{-   end -}}
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: bivac-providers-conf
              mountPath: /etc/bivac
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: bivac-providers-conf
          configMap:
            name: {{ .Release.Name }}
